[MeasureAudio1]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-1))

[MeterBar1]
Meter=Bar
MeasureName=MeasureAudio1

[MeasureAudio2]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-2))

[MeterBar2]
Meter=Bar
MeasureName=MeasureAudio2

[MeasureAudio3]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-3))

[MeterBar3]
Meter=Bar
MeasureName=MeasureAudio3

[MeasureAudio4]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-4))

[MeterBar4]
Meter=Bar
MeasureName=MeasureAudio4

[MeasureAudio5]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-5))

[MeterBar5]
Meter=Bar
MeasureName=MeasureAudio5

[MeasureAudio6]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-6))

[MeterBar6]
Meter=Bar
MeasureName=MeasureAudio6

[MeasureAudio7]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-7))

[MeterBar7]
Meter=Bar
MeasureName=MeasureAudio7

[MeasureAudio8]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-8))

[MeterBar8]
Meter=Bar
MeasureName=MeasureAudio8

[MeasureAudio9]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-9))

[MeterBar9]
Meter=Bar
MeasureName=MeasureAudio9

[MeasureAudio10]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-10))

[MeterBar10]
Meter=Bar
MeasureName=MeasureAudio10

[MeasureAudio11]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-11))

[MeterBar11]
Meter=Bar
MeasureName=MeasureAudio11

[MeasureAudio12]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-12))

[MeterBar12]
Meter=Bar
MeasureName=MeasureAudio12

[MeasureAudio13]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-13))

[MeterBar13]
Meter=Bar
MeasureName=MeasureAudio13

[MeasureAudio14]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-14))

[MeterBar14]
Meter=Bar
MeasureName=MeasureAudio14

[MeasureAudio15]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-15))

[MeterBar15]
Meter=Bar
MeasureName=MeasureAudio15

[MeasureAudio16]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-16))

[MeterBar16]
Meter=Bar
MeasureName=MeasureAudio16

[MeasureAudio17]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-17))

[MeterBar17]
Meter=Bar
MeasureName=MeasureAudio17

[MeasureAudio18]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-18))

[MeterBar18]
Meter=Bar
MeasureName=MeasureAudio18

[MeasureAudio19]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-19))

[MeterBar19]
Meter=Bar
MeasureName=MeasureAudio19

[MeasureAudio20]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-20))

[MeterBar20]
Meter=Bar
MeasureName=MeasureAudio20

[MeasureAudio21]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-21))

[MeterBar21]
Meter=Bar
MeasureName=MeasureAudio21

[MeasureAudio22]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-22))

[MeterBar22]
Meter=Bar
MeasureName=MeasureAudio22

[MeasureAudio23]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-23))

[MeterBar23]
Meter=Bar
MeasureName=MeasureAudio23

[MeasureAudio24]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-24))

[MeterBar24]
Meter=Bar
MeasureName=MeasureAudio24

[MeasureAudio25]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-25))

[MeterBar25]
Meter=Bar
MeasureName=MeasureAudio25

[MeasureAudio26]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-26))

[MeterBar26]
Meter=Bar
MeasureName=MeasureAudio26

[MeasureAudio27]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-27))

[MeterBar27]
Meter=Bar
MeasureName=MeasureAudio27

[MeasureAudio28]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-28))

[MeterBar28]
Meter=Bar
MeasureName=MeasureAudio28

[MeasureAudio29]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-29))

[MeterBar29]
Meter=Bar
MeasureName=MeasureAudio29

[MeasureAudio30]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-30))

[MeterBar30]
Meter=Bar
MeasureName=MeasureAudio30

[MeasureAudio31]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-31))

[MeterBar31]
Meter=Bar
MeasureName=MeasureAudio31

[MeasureAudio32]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-32))

[MeterBar32]
Meter=Bar
MeasureName=MeasureAudio32

[MeasureAudio33]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-33))

[MeterBar33]
Meter=Bar
MeasureName=MeasureAudio33

[MeasureAudio34]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-34))

[MeterBar34]
Meter=Bar
MeasureName=MeasureAudio34

[MeasureAudio35]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-35))

[MeterBar35]
Meter=Bar
MeasureName=MeasureAudio35

[MeasureAudio36]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-36))

[MeterBar36]
Meter=Bar
MeasureName=MeasureAudio36

[MeasureAudio37]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-37))

[MeterBar37]
Meter=Bar
MeasureName=MeasureAudio37

[MeasureAudio38]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-38))

[MeterBar38]
Meter=Bar
MeasureName=MeasureAudio38

[MeasureAudio39]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-39))

[MeterBar39]
Meter=Bar
MeasureName=MeasureAudio39

[MeasureAudio40]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-40))

[MeterBar40]
Meter=Bar
MeasureName=MeasureAudio40

[MeasureAudio41]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-41))

[MeterBar41]
Meter=Bar
MeasureName=MeasureAudio41

[MeasureAudio42]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-42))

[MeterBar42]
Meter=Bar
MeasureName=MeasureAudio42

[MeasureAudio43]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-43))

[MeterBar43]
Meter=Bar
MeasureName=MeasureAudio43

[MeasureAudio44]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-44))

[MeterBar44]
Meter=Bar
MeasureName=MeasureAudio44

[MeasureAudio45]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-45))

[MeterBar45]
Meter=Bar
MeasureName=MeasureAudio45

[MeasureAudio46]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-46))

[MeterBar46]
Meter=Bar
MeasureName=MeasureAudio46

[MeasureAudio47]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-47))

[MeterBar47]
Meter=Bar
MeasureName=MeasureAudio47

[MeasureAudio48]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-48))

[MeterBar48]
Meter=Bar
MeasureName=MeasureAudio48

[MeasureAudio49]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-49))

[MeterBar49]
Meter=Bar
MeasureName=MeasureAudio49

[MeasureAudio50]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-50))

[MeterBar50]
Meter=Bar
MeasureName=MeasureAudio50

[MeasureAudio51]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-51))

[MeterBar51]
Meter=Bar
MeasureName=MeasureAudio51

[MeasureAudio52]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-52))

[MeterBar52]
Meter=Bar
MeasureName=MeasureAudio52

[MeasureAudio53]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-53))

[MeterBar53]
Meter=Bar
MeasureName=MeasureAudio53

[MeasureAudio54]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-54))

[MeterBar54]
Meter=Bar
MeasureName=MeasureAudio54

[MeasureAudio55]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-55))

[MeterBar55]
Meter=Bar
MeasureName=MeasureAudio55

[MeasureAudio56]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-56))

[MeterBar56]
Meter=Bar
MeasureName=MeasureAudio56

[MeasureAudio57]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-57))

[MeterBar57]
Meter=Bar
MeasureName=MeasureAudio57

[MeasureAudio58]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-58))

[MeterBar58]
Meter=Bar
MeasureName=MeasureAudio58

[MeasureAudio59]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-59))

[MeterBar59]
Meter=Bar
MeasureName=MeasureAudio59

[MeasureAudio60]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-60))

[MeterBar60]
Meter=Bar
MeasureName=MeasureAudio60

[MeasureAudio61]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-61))

[MeterBar61]
Meter=Bar
MeasureName=MeasureAudio61

[MeasureAudio62]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-62))

[MeterBar62]
Meter=Bar
MeasureName=MeasureAudio62

[MeasureAudio63]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-63))

[MeterBar63]
Meter=Bar
MeasureName=MeasureAudio63

[MeasureAudio64]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-64))

[MeterBar64]
Meter=Bar
MeasureName=MeasureAudio64

[MeasureAudio65]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-65))

[MeterBar65]
Meter=Bar
MeasureName=MeasureAudio65

[MeasureAudio66]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-66))

[MeterBar66]
Meter=Bar
MeasureName=MeasureAudio66

[MeasureAudio67]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-67))

[MeterBar67]
Meter=Bar
MeasureName=MeasureAudio67

[MeasureAudio68]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-68))

[MeterBar68]
Meter=Bar
MeasureName=MeasureAudio68

[MeasureAudio69]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-69))

[MeterBar69]
Meter=Bar
MeasureName=MeasureAudio69

[MeasureAudio70]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-70))

[MeterBar70]
Meter=Bar
MeasureName=MeasureAudio70

[MeasureAudio71]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-71))

[MeterBar71]
Meter=Bar
MeasureName=MeasureAudio71

[MeasureAudio72]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-72))

[MeterBar72]
Meter=Bar
MeasureName=MeasureAudio72

[MeasureAudio73]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-73))

[MeterBar73]
Meter=Bar
MeasureName=MeasureAudio73

[MeasureAudio74]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-74))

[MeterBar74]
Meter=Bar
MeasureName=MeasureAudio74

[MeasureAudio75]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-75))

[MeterBar75]
Meter=Bar
MeasureName=MeasureAudio75

[MeasureAudio76]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-76))

[MeterBar76]
Meter=Bar
MeasureName=MeasureAudio76

[MeasureAudio77]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-77))

[MeterBar77]
Meter=Bar
MeasureName=MeasureAudio77

[MeasureAudio78]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-78))

[MeterBar78]
Meter=Bar
MeasureName=MeasureAudio78

[MeasureAudio79]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=(Abs((#Invert# = 1 ? #Bands# : 0)-79))

[MeterBar79]
Meter=Bar
MeasureName=MeasureAudio79