[ChameleonDesktop]
Measure=Plugin
Group=Chameleon
Plugin=Chameleon
Type=Desktop

[DesktopAvg]
Measure=Plugin
Group=Chameleon
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Average

[DesktopFG1]
Measure=Plugin
Group=Chameleon
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Foreground1

[DesktopBG1]
Measure=Plugin
Group=Chameleon
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Background1

[DesktopFG2]
Measure=Plugin
Group=Chameleon
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Foreground2

[DesktopBG2]
Measure=Plugin
Group=Chameleon
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Background2