[ChameleonDesktop]
Measure=Plugin
Group=Chameleon
Plugin=Chameleon
Type=Desktop

[DesktopBG1]
Measure=Plugin
Group=Chameleon
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Background1

[DesktopFG1]
Measure=Plugin
Group=Chameleon
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Foreground1

[DesktopBG2]
Measure=Plugin
Group=Chameleon
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Background2

[DesktopFG2]
Measure=Plugin
Group=Chameleon
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Foreground2