[Rainmeter]
Update=0
DefaultUpdateDivider=-1
Group=FountainOfColors

ContextTitle="Options..."
ContextAction=[!ActivateConfig "Fountain of Colors\SettingsWindowTest"]

OnRefreshAction=

[MeasureAudio]
Measure=Plugin
Plugin=AudioLevel
Port=Output
ID=
FFTSize=4096
FFTOverlap=2490
FFTAttack=-1
FFTDecay=-1
Bands=60
FreqMin=16.352
FreqMax=16744.036 
Sensitivity=39
UpdateDivider=1

[Include]
@Include=#@#Bands.inc

@Include2=
@Include3=
@Include4=
@Include5=
