[Rainmeter]
Update=0
DefaultUpdateDivider=-1
Group=FountainOfColors
LeftMouseUpAction=[!ActivateConfig "Fountain of Colors\SettingsWindow"]

OnRefreshAction=

[MeasureAudio]
Measure=Plugin
Plugin=AudioLevel
Port=Output
ID=
RMSAttack=0
RMSDecay=0
RMSGain=1
PeakAttack=0
PeakDecay=0
PeakGain=1
FFTSize=4096
FFTOverlap=3584
FFTAttack=0
FFTDecay=22
Bands=56
FreqMin=33
FreqMax=14000
Sensitivity=48.1645
UpdateDivider=1

[Include]
@Include=

@Include2=
@Include3=
@Include4=
@Include5=
