[Variables]

; Save this text file and refresh the skin after editing these settings!

Bands=80
BarGap=7
BarWidth=12
BarHeight=400

BarColor=008000
; Overriden by the ColorChanger script if enabled

AverageSize=4
; Number of past measure values to average from, increasing continuity

Port=Output
ID=""
FFTSize=9216
FFTOverlap=(#FFTSize#*0.5)
FFTAttack=300
FFTDecay=300
FreqMin=20
FreqMax=16000
Sensitivity=40
; http://docs.rainmeter.net/manual-beta/plugins/audiolevel

ColorIntensity=1.25
ColorTransitionTime=4
ColorUpdatesPerSecond=62.5
ColorPlaylist=RandomColorPlaylist
; See ColorPlaylists.inc

PlayerName=CAD
; http://docs.rainmeter.net/manual-beta/plugins/nowplaying#playerlist

; Context menu environment variables
Config=Fountain of Colors
ConfigPath=C:\Users\YourName\My Documents\Rainmeter\Skins\Fountain of Colors\Fountain of Colors.ini
Angle=0
