[MeasureAudio1]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=1

[MeterBar1]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio1

[MeasureAudio2]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=2

[MeterBar2]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio2

[MeasureAudio3]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=3

[MeterBar3]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio3

[MeasureAudio4]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=4

[MeterBar4]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio4

[MeasureAudio5]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=5

[MeterBar5]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio5

[MeasureAudio6]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=6

[MeterBar6]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio6

[MeasureAudio7]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=7

[MeterBar7]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio7

[MeasureAudio8]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=8

[MeterBar8]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio8

[MeasureAudio9]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=9

[MeterBar9]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio9

[MeasureAudio10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=10

[MeterBar10]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio10

[MeasureAudio11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=11

[MeterBar11]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio11

[MeasureAudio12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=12

[MeterBar12]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio12

[MeasureAudio13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=13

[MeterBar13]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio13

[MeasureAudio14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=14

[MeterBar14]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio14

[MeasureAudio15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=15

[MeterBar15]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio15

[MeasureAudio16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=16

[MeterBar16]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio16

[MeasureAudio17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=17

[MeterBar17]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio17

[MeasureAudio18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=18

[MeterBar18]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio18

[MeasureAudio19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=19

[MeterBar19]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio19

[MeasureAudio20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=20

[MeterBar20]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio20

[MeasureAudio21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=21

[MeterBar21]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio21

[MeasureAudio22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=22

[MeterBar22]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio22

[MeasureAudio23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=23

[MeterBar23]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio23

[MeasureAudio24]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=24

[MeterBar24]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio24

[MeasureAudio25]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=25

[MeterBar25]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio25

[MeasureAudio26]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=26

[MeterBar26]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio26

[MeasureAudio27]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=27

[MeterBar27]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio27

[MeasureAudio28]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=28

[MeterBar28]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio28

[MeasureAudio29]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=29

[MeterBar29]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio29

[MeasureAudio30]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=30

[MeterBar30]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio30

[MeasureAudio31]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=31

[MeterBar31]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio31

[MeasureAudio32]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=32

[MeterBar32]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio32

[MeasureAudio33]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=33

[MeterBar33]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio33

[MeasureAudio34]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=34

[MeterBar34]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio34

[MeasureAudio35]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=35

[MeterBar35]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio35

[MeasureAudio36]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=36

[MeterBar36]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio36

[MeasureAudio37]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=37

[MeterBar37]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio37

[MeasureAudio38]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=38

[MeterBar38]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio38

[MeasureAudio39]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=39

[MeterBar39]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio39

[MeasureAudio40]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=40

[MeterBar40]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio40

[MeasureAudio41]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=41

[MeterBar41]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio41

[MeasureAudio42]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=42

[MeterBar42]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio42

[MeasureAudio43]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=43

[MeterBar43]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio43

[MeasureAudio44]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=44

[MeterBar44]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio44

[MeasureAudio45]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=45

[MeterBar45]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio45

[MeasureAudio46]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=46

[MeterBar46]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio46

[MeasureAudio47]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=47

[MeterBar47]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio47

[MeasureAudio48]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=48

[MeterBar48]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio48

[MeasureAudio49]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=49

[MeterBar49]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio49

[MeasureAudio50]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=50

[MeterBar50]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio50

[MeasureAudio51]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=51

[MeterBar51]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio51

[MeasureAudio52]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=52

[MeterBar52]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio52

[MeasureAudio53]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=53

[MeterBar53]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio53

[MeasureAudio54]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=54

[MeterBar54]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio54

[MeasureAudio55]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=55

[MeterBar55]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio55

[MeasureAudio56]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=56

[MeterBar56]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio56

[MeasureAudio57]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=57

[MeterBar57]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio57

[MeasureAudio58]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=58

[MeterBar58]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio58

[MeasureAudio59]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=59

[MeterBar59]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio59

[MeasureAudio60]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=60

[MeterBar60]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio60

[MeasureAudio61]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=61

[MeterBar61]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio61

[MeasureAudio62]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=62

[MeterBar62]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio62

[MeasureAudio63]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=63

[MeterBar63]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio63

[MeasureAudio64]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=64

[MeterBar64]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio64

[MeasureAudio65]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=65

[MeterBar65]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio65

[MeasureAudio66]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=66

[MeterBar66]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio66

[MeasureAudio67]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=67

[MeterBar67]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio67

[MeasureAudio68]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=68

[MeterBar68]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio68

[MeasureAudio69]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=69

[MeterBar69]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio69

[MeasureAudio70]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=70

[MeterBar70]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio70

[MeasureAudio71]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=71

[MeterBar71]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio71

[MeasureAudio72]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=72

[MeterBar72]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio72

[MeasureAudio73]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=73

[MeterBar73]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio73

[MeasureAudio74]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=74

[MeterBar74]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio74

[MeasureAudio75]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=75

[MeterBar75]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio75

[MeasureAudio76]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=76

[MeterBar76]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio76

[MeasureAudio77]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=77

[MeterBar77]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio77

[MeasureAudio78]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=78

[MeterBar78]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio78

[MeasureAudio79]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=79

[MeterBar79]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio79

[MeasureAudio80]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=80

[MeterBar80]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio80

[MeasureAudio81]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=81

[MeterBar81]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio81

[MeasureAudio82]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=82

[MeterBar82]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio82

[MeasureAudio83]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=83

[MeterBar83]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio83

[MeasureAudio84]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=84

[MeterBar84]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio84

[MeasureAudio85]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=85

[MeterBar85]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio85

[MeasureAudio86]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=86

[MeterBar86]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio86

[MeasureAudio87]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=87

[MeterBar87]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio87

[MeasureAudio88]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=88

[MeterBar88]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio88

[MeasureAudio89]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=89

[MeterBar89]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio89

[MeasureAudio90]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=90

[MeterBar90]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio90

[MeasureAudio91]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=91

[MeterBar91]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio91

[MeasureAudio92]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=92

[MeterBar92]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio92

[MeasureAudio93]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=93

[MeterBar93]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio93

[MeasureAudio94]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=94

[MeterBar94]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio94

[MeasureAudio95]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=95

[MeterBar95]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio95