[MeasureAudio1]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=1
AverageSize=#AverageSize#

[MeterBar1]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio1

[MeasureAudio2]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=2
AverageSize=#AverageSize#

[MeterBar2]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio2

[MeasureAudio3]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=3
AverageSize=#AverageSize#

[MeterBar3]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio3

[MeasureAudio4]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=4
AverageSize=#AverageSize#

[MeterBar4]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio4

[MeasureAudio5]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=5
AverageSize=#AverageSize#

[MeterBar5]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio5

[MeasureAudio6]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=6
AverageSize=#AverageSize#

[MeterBar6]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio6

[MeasureAudio7]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=7
AverageSize=#AverageSize#

[MeterBar7]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio7

[MeasureAudio8]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=8
AverageSize=#AverageSize#

[MeterBar8]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio8

[MeasureAudio9]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=9
AverageSize=#AverageSize#

[MeterBar9]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio9

[MeasureAudio10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=10
AverageSize=#AverageSize#

[MeterBar10]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio10

[MeasureAudio11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=11
AverageSize=#AverageSize#

[MeterBar11]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio11

[MeasureAudio12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=12
AverageSize=#AverageSize#

[MeterBar12]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio12

[MeasureAudio13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=13
AverageSize=#AverageSize#

[MeterBar13]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio13

[MeasureAudio14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=14
AverageSize=#AverageSize#

[MeterBar14]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio14

[MeasureAudio15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=15
AverageSize=#AverageSize#

[MeterBar15]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio15

[MeasureAudio16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=16
AverageSize=#AverageSize#

[MeterBar16]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio16

[MeasureAudio17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=17
AverageSize=#AverageSize#

[MeterBar17]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio17

[MeasureAudio18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=18
AverageSize=#AverageSize#

[MeterBar18]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio18

[MeasureAudio19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=19
AverageSize=#AverageSize#

[MeterBar19]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio19

[MeasureAudio20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=20
AverageSize=#AverageSize#

[MeterBar20]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio20

[MeasureAudio21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=21
AverageSize=#AverageSize#

[MeterBar21]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio21

[MeasureAudio22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=22
AverageSize=#AverageSize#

[MeterBar22]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio22

[MeasureAudio23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=23
AverageSize=#AverageSize#

[MeterBar23]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio23

[MeasureAudio24]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=24
AverageSize=#AverageSize#

[MeterBar24]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio24

[MeasureAudio25]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=25
AverageSize=#AverageSize#

[MeterBar25]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio25

[MeasureAudio26]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=26
AverageSize=#AverageSize#

[MeterBar26]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio26

[MeasureAudio27]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=27
AverageSize=#AverageSize#

[MeterBar27]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio27

[MeasureAudio28]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=28
AverageSize=#AverageSize#

[MeterBar28]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio28

[MeasureAudio29]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=29
AverageSize=#AverageSize#

[MeterBar29]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio29

[MeasureAudio30]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=30
AverageSize=#AverageSize#

[MeterBar30]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio30

[MeasureAudio31]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=31
AverageSize=#AverageSize#

[MeterBar31]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio31

[MeasureAudio32]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=32
AverageSize=#AverageSize#

[MeterBar32]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio32

[MeasureAudio33]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=33
AverageSize=#AverageSize#

[MeterBar33]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio33

[MeasureAudio34]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=34
AverageSize=#AverageSize#

[MeterBar34]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio34

[MeasureAudio35]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=35
AverageSize=#AverageSize#

[MeterBar35]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio35

[MeasureAudio36]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=36
AverageSize=#AverageSize#

[MeterBar36]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio36

[MeasureAudio37]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=37
AverageSize=#AverageSize#

[MeterBar37]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio37

[MeasureAudio38]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=38
AverageSize=#AverageSize#

[MeterBar38]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio38

[MeasureAudio39]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=39
AverageSize=#AverageSize#

[MeterBar39]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio39

[MeasureAudio40]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=40
AverageSize=#AverageSize#

[MeterBar40]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio40

[MeasureAudio41]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=41
AverageSize=#AverageSize#

[MeterBar41]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio41

[MeasureAudio42]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=42
AverageSize=#AverageSize#

[MeterBar42]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio42

[MeasureAudio43]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=43
AverageSize=#AverageSize#

[MeterBar43]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio43

[MeasureAudio44]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=44
AverageSize=#AverageSize#

[MeterBar44]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio44

[MeasureAudio45]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=45
AverageSize=#AverageSize#

[MeterBar45]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio45

[MeasureAudio46]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=46
AverageSize=#AverageSize#

[MeterBar46]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio46

[MeasureAudio47]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=47
AverageSize=#AverageSize#

[MeterBar47]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio47

[MeasureAudio48]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=48
AverageSize=#AverageSize#

[MeterBar48]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio48

[MeasureAudio49]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=49
AverageSize=#AverageSize#

[MeterBar49]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio49

[MeasureAudio50]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=50
AverageSize=#AverageSize#

[MeterBar50]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio50

[MeasureAudio51]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=51
AverageSize=#AverageSize#

[MeterBar51]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio51

[MeasureAudio52]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=52
AverageSize=#AverageSize#

[MeterBar52]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio52

[MeasureAudio53]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=53
AverageSize=#AverageSize#

[MeterBar53]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio53

[MeasureAudio54]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=54
AverageSize=#AverageSize#

[MeterBar54]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio54

[MeasureAudio55]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=55
AverageSize=#AverageSize#

[MeterBar55]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio55

[MeasureAudio56]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=56
AverageSize=#AverageSize#

[MeterBar56]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio56

[MeasureAudio57]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=57
AverageSize=#AverageSize#

[MeterBar57]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio57

[MeasureAudio58]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=58
AverageSize=#AverageSize#

[MeterBar58]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio58

[MeasureAudio59]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=59
AverageSize=#AverageSize#

[MeterBar59]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio59

[MeasureAudio60]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=60
AverageSize=#AverageSize#

[MeterBar60]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio60

[MeasureAudio61]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=61
AverageSize=#AverageSize#

[MeterBar61]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio61

[MeasureAudio62]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=62
AverageSize=#AverageSize#

[MeterBar62]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio62

[MeasureAudio63]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=63
AverageSize=#AverageSize#

[MeterBar63]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio63

[MeasureAudio64]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=64
AverageSize=#AverageSize#

[MeterBar64]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio64

[MeasureAudio65]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=65
AverageSize=#AverageSize#

[MeterBar65]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio65

[MeasureAudio66]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=66
AverageSize=#AverageSize#

[MeterBar66]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio66

[MeasureAudio67]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=67
AverageSize=#AverageSize#

[MeterBar67]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio67

[MeasureAudio68]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=68
AverageSize=#AverageSize#

[MeterBar68]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio68

[MeasureAudio69]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=69
AverageSize=#AverageSize#

[MeterBar69]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio69

[MeasureAudio70]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=70
AverageSize=#AverageSize#

[MeterBar70]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio70

[MeasureAudio71]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=71
AverageSize=#AverageSize#

[MeterBar71]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio71